version: '3.1'

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports:
        - 127.0.0.1:9002:9002

    server:
        build: .
        environment:
            PGHOST:     postgres
            PGPORT:     5432
            PGDATABASE: postgres
            PGUSER:     postgres
            PGPASSWORD: password
        depends_on:
            - postgres
        ports:
            - 127.0.0.1:9001:8000
        volumes:
            - ./secrets:/secrets
